sudo: required
dist: trusty
language: cpp

before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt58-trusty
  - sudo apt-get update -qq

install:
  - sudo apt-get install qt58base qt58websockets

script:
  - qmake -project
  - qmake lab8.pro
  - make
