sudo: required
dist: trusty
language: cpp

before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt58-trusty
  - sudo apt-get update -qq
  - sudo apt-get install <QJsonDocument>
  - sudo apt-get install <QJsonArray>
  - sudo apt-get install <QJsonObject>
  - sudo apt-get install <QFile>
  - sudo apt-get install <QTextStream>
  

install:
  - sudo apt-get install qt58base
  - sudo apt-get install libssl-dev
  - sh scripts/install-libprogbase.sh

script:
  - qmake -project
  - qmake lab8.pro
  - make
